version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "del"
        versions: ["7.x"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
