# Config

source: ./source
destination: ./build

# Environment
env: production

# Meta
encoding: UTF-8
timezone: Europe/London
baseurl: ""
url: "http://davidrapson.co.uk"

# Details
title: David Rapson
email: david@davidrapson.co.uk
description: David Rapson makes websites.
profile_image: https://www.gravatar.com/avatar/ff58211f1f9ee8802ae7a66aa7a08dcd.png?s=150
twitter_username: davidrapson
github_username:  davidrapson

# Permalinks
permalink: /:year/:title/

# Pagination
paginate: 6
paginate_path: "page-:num/"

# Writing
# See: https://github.com/jekyll/jekyll/issues/3371
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    inline_theme: github

# Responsive images
picture:
  source: "assets/images"
  output: "images"
  presets:
    default:
      source_4:
        width: "800"
      source_3:
        width: "600"
      source_2:
        width: "480"
      source_1:
        width: "320"
      source_default:
        width: "320"

# Build Excludes
exclude: [
  "assets"
]

# PLugins
gems:
  - jekyll-sitemap
