# Config

# Site settings
title: David Rapson
email: david@davidrapson.co.uk
description: David Rapson is a client-side developer living and working in London, originally from Birmingham.
twitter_username: davidrapson
github_username:  davidrapson

# URLs
baseurl: ""
url: "http://davidrapson.co.uk"
cdn_url: static.davidrapson.co.uk
permalink: /:year/:title/

# Pagination
paginate: 5

# Environment
env: production

# Gems
gems:
  - jekyll-sitemap

# Build Excludes
exclude: [
  "assets",
  "bin",
  "bower.json",
  "config.json",
  "davidrapson.sublime-project",
  "davidrapson.sublime-workspace",
  "Gemfile",
  "Gemfile.lock",
  "gulpfile",
  "lib",
  "node_modules",
  "package.json",
  "README.md",
  "secrets.json",
  "setup.sh",
  "tasks"
]

# jekyll-picture-teg settings
picture:
  source: "assets/images"
  output: "images"
  markup: "img"
  lazysizes: true
  presets:
    default:
      source_4:
        width: "800"
      source_3:
        width: "600"
      source_2:
        width: "480"
      source_1:
        width: "320"
      source_default:
        width: "480"

# Gems
markdown: Pypedown
gems:
  - jekyll-pypedown
  - jekyll-minify-html
