# Config

# Site settings
title: David Rapson
email: david@davidrapson.co.uk
description: David Rapson is a client-side developer living and working in London, originally from Birmingham.
twitter_username: davidrapson
github_username:  davidrapson

# URLs
baseurl: ""
url: "http://davidrapson.co.uk"
cdn_url: static.davidrapson.co.uk
permalink: /:year/:title/

# Pagination
paginate: 5

# Environment
env: production

# Build Excludes
exclude: [
  "README.md",
  "node_modules",
  "bin",
  "gulpfile",
  "Gemfile",
  "Gemfile.lock",
  "bower.json",
  "package.json",
  "secrets.json",
  "static/css/less/"
]

# jekyll-picture-teg settings
picture:
  source: "images/src"
  output: "images/output"
  markup: "picture"
  presets:
    default:
      source_large:
        media: "(min-width: 45em)"
        width: "800"
      source_medium:
        media: "(min-width: 30em)"
        width: "600"
      source_small:
        media: "(min-width: 20em)"
        width: "480"
      source_default:
        width: "320"

# Gems
markdown: Pypedown
gems:
  - jekyll-pypedown
  - jekyll-minify-html
