# Config

source: ./source
destination: ./build

# Environment
env: production

# Details
title: David Rapson
email: david@davidrapson.co.uk
description: David Rapson is a client-side developer living and working in London, originally from Birmingham.
twitter_username: davidrapson
github_username:  davidrapson

# Config
baseurl: ""
url: "http://davidrapson.co.uk"
cdn_url: static.davidrapson.co.uk
permalink: /:year/:title/
timezone: Europe/London
paginate: 6

# Responsive images
picture:
  source: "assets/images"
  output: "images"
  markup: "img"
  lazysizes: true
  presets:
    default:
      source_4:
        width: "800"
      source_3:
        width: "600"
      source_2:
        width: "480"
      source_1:
        width: "320"
      source_default:
        width: "480"

# Build Excludes
exclude: [
  "assets"
]

# Gems
markdown: Pypedown
gems:
  - jekyll-sitemap
  - jekyll-pypedown
  - jekyll-minify-html
