[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; font-src fonts.gstatic.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; script-src 'unsafe-inline'"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
